name: Autograding

on: [push]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run student script
      run: |
        mkdir -p logs
        python src/main.py

    - name: Check logs
      run: |
        grep -q "PARSE_JSON_SUCCESS" logs/lab.log
        grep -q "PARSE_YAML_SUCCESS" logs/lab.log
        grep -q "PARSE_XML_SUCCESS" logs/lab.log
        grep -q "PARSE_CSV_SUCCESS" logs/lab.log
        grep -q "DEVICE_SUMMARY" logs/lab.log